include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
  errors:
    missing_return: error
    prefer_if_elements_to_conditional_expressions: false
    missing_required_param: error
    must_be_immutable: error

  #    prefer_if_elements_to_conditional_expressions:true
